version: "3.9"
services:
  db:
    image: postgres:15
    container_name: catalogo-db
    environment:
      POSTGRES_USER: catalogo
      POSTGRES_PASSWORD: catalogo
      POSTGRES_DB: catalogo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: catalogo-backend
    environment:
      DATABASE_URL: postgresql://catalogo:catalogo@db:5432/catalogo
      PORT: 4000
    depends_on:
      - db
    ports:
      - "0.0.0.0:4000:4000"

  web:
    build: ./web
    container_name: catalogo-web
    environment:
      NEXT_PUBLIC_API_BASE: http://192.168.1.39:4000
    depends_on:
      - backend
    ports:
      - "3000:3000"

volumes:
  pgdata:
